// <auto-generated />
namespace DAO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class status_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(status_added));
        
        string IMigrationMetadata.Id
        {
            get { return "201601201543483_status_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
